### ISSUE TITLE
Warning when building the kernel

### ISSUE THREAD

**Issue by Hadenix** [JamiKettunen/android_kernel_volla_mt6763#1]
got this when changing LCM to its own

```
Warning (reg_format): "reg" property in /fragment@34/__overlay__/MT5715_receiver@56 has invalid length (4 bytes) (#address-cells == 2, #size-cells == 1)
Warning (reg_format): "reg" property in /fragment@35/__overlay__/spc@40 has invalid length (4 bytes) (#address-cells == 2, #size-cells == 1)
Warning (ranges_format): /fragment@0/__overlay__ has empty "ranges" property but its #size-cells (2) differs from /fragment@0 (1)
Warning (avoid_default_addr_size): Relying on default #address-cells value for /fragment@0/__overlay__
Warning (avoid_default_addr_size): Relying on default #size-cells value for /fragment@0/__overlay__
Warning (avoid_default_addr_size): Relying on default #address-cells value for /fragment@34/__overlay__/MT5715_receiver@56
Warning (avoid_default_addr_size): Relying on default #size-cells value for /fragment@34/__overlay__/MT5715_receiver@56
Warning (avoid_default_addr_size): Relying on default #address-cells value for /fragment@35/__overlay__/spc@40
Warning (avoid_default_addr_size): Relying on default #size-cells value for /fragment@35/__overlay__/spc@40
Warning (reg_format): "reg" property in /i2c@11011000/rt9465@4b has invalid length (4 bytes) (#address-cells == 2, #size-cells == 1)
Warning (avoid_default_addr_size): Relying on default #address-cells value for /i2c@11011000/rt9465@4b
Warning (avoid_default_addr_size): Relying on default #size-cells value for /i2c@11011000/rt9465@4b

```

**Comment by JamiKettunen** [comment]
I know this is an issue, I really do not want to fix DTS warnings and I'm not sure if most of these can even be fixed because they're from compiling a DTS Overlay.

**Comment by Hadenix** [comment]
> I know this is an issue, I really do not want to fix DTS warnings and I'm not sure if most of these can even be fixed because they're from compiling a DTS Overlay.

I just specified. as I saw that I removed a lot of things.

**Comment by Hadenix** [comment]
> I know this is an issue, I really do not want to fix DTS warnings and I'm not sure if most of these can even be fixed because they're from compiling a DTS Overlay.

boot.img: 1 file pushed. 15.7 MB/s (9326592 bytes in 0.566s)
kernel-modules.tar.gz: 1 file pushed. 14.7 MB/s (796933 bytes in 0.052s)
2 files pushed. 15.5 MB/s (10123525 bytes in 0.622s)
dd: block size `4M': illegal number
tar: chdir '/system/lib/modules/'
chown: /system/lib/modules/*: No such file or directory
>> Done!

**Comment by JamiKettunen** [comment]
@Hadenix Which OS do you have flashed on the device? I've only ever tested the scripts (and kernel in general) against Ubuntu Touch on the `halium-9.0` branch besides just checking if compiling still works.

**Comment by Hadenix** [comment]
> @Hadenix Which OS do you have flashed on the device? I've only ever tested the scripts (and kernel in general) against Ubuntu Touch on the `halium-9.0` branch besides just checking if compiling still works.

Linux Mint 20/ I am using master branch and want to build a kernel for my android phone

**Comment by JamiKettunen** [comment]
Am I misunderstanding something or do you not have a Volla Phone? If you don't sorry but good luck with these sources. You'd need to make a device specific DTS, write device specific drivers so hardware actually works etc etc and I don't know how you'd go about doing that with the tools in this v4.4 Android kernel tree and especially if you have no kernel sources for your own device.

**Comment by Hadenix** [comment]
```
$ git clone https://github.com/JamiKettunen/android_kernel_volla_mt6763.git
Cloning into 'android_kernel_volla_mt6763'...
remote: Enumerating objects: 5608, done.
remote: Counting objects: 100% (5608/5608), done.
remote: Compressing objects: 100% (1846/1846), done.
remote: Total 4623214 (delta 4238), reused 4300 (delta 3760), pack-reused 4617606
Receiving objects: 100% (4623214/4623214), 852.12 MiB | 1.52 MiB/s, done.
Resolving deltas: 100% (3871252/3871252), done.
error: invalid path 'drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.c'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

```

**Comment by JamiKettunen** [comment]
@Hadenix You did not answer my last question though, I just cloned this same repo with the exact same command locally on my machine and it worked without issues :man_shrugging:

**Comment by JamiKettunen** [comment]
@Hadenix https://github.com/Hadenix/android_kernel_volla_mt6763/commit/f0262bc977728b6a85b0329f4fe6f9b14f633680 I see you're trying to create a kernel port for for the UMIDIGI A5 Pro (breeze); here's a few pointers:
1. This kernel repo *might* currently have partially or fully broken code depending on what config options are chosen (even sometimes despite them compiling fine) as I've merged in commits from linux-stable (and Google). Most likely starting with [my tagged base tree](https://github.com/JamiKettunen/android_kernel_volla_mt6763/tree/v4.4.146) and (cross-)compiling under an Ubuntu 16.04 chroot/container with GCC 4 or 5 would be a wise idea.
2. Do not try to use any of my build/deployment scripts as they were specifically made with the Volla Phone in mind; instead use them as reference/guidelines or check other online kernel (cross-)compilation guides and do things manually till you get the workflow down, then write script(s) to do those things for you.
3. I assume you already have some kind of BSP DTS for the device created from the extracted DTB which is appended in the `zImage-dtb` (which is what the kernel's filename should be)? You should look into the Device Tree format a bit and try to clean it up at least a little bit so it's more readable for you as well (you could use the existing `k63v2_64_bsp` files as help).
4. Finally when creating a boot image make sure you use all the correct offsets and such for everything; the Volla Phone just enters an infinite bootloop with nothing on display for example if the bootloader can't find `bootopt=64S3,32N2,64N2` as a cmdline parameter in the final Android `boot.img` (similar things can also happen if something's wrong with the DTB in the kernel image, but that shouldn't be a problem if you re-use the existing one from your phone's OFW).
5. Getting UART serial output might be a worth investment to get logs from the bootloader if you really want to go through with this; I've never done this personally on any device so I'm the wrong person to ask however.
